# Generated by Django 6.0.7 on 2026-07-15 14:21

import django.core.validators
import django.db.models.deletion
import reclamations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        ('hebergement', '0003_affectation_transfert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description du problème')),
                ('categorie', models.CharField(choices=[('ELECTRICITE', 'Électricité'), ('PLOMBERIE', 'Plomberie'), ('MOBILIER', 'Mobilier'), ('INTERNET', 'Connexion Internet'), ('PROPRETE', 'Propreté'), ('SECURITE', 'Sécurité'), ('CONFLIT', 'Conflit entre étudiants'), ('AUTRE', 'Autre')], max_length=15, verbose_name='Catégorie')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_COURS', 'En cours de traitement'), ('RESOLUE', 'Résolue'), ('REJETEE', 'Rejetée'), ('FERMEE', 'Fermée')], default='NOUVELLE', max_length=10, verbose_name='Statut')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='reclamations/pieces_jointes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), reclamations.models.valider_taille_piece_jointe], verbose_name='Pièce jointe')),
                ('nom_original_piece', models.CharField(blank=True, max_length=255, verbose_name='Nom original de la pièce jointe')),
                ('reponse', models.TextField(blank=True, verbose_name='Réponse du responsable')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif du rejet')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_prise_en_charge', models.DateTimeField(blank=True, null=True, verbose_name='Date de prise en charge')),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('date_fermeture', models.DateTimeField(blank=True, null=True, verbose_name='Date de fermeture')),
                ('chambre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='hebergement.chambre', verbose_name='Chambre concernée')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='etudiants.etudiant', verbose_name='Étudiant')),
                ('traitee_par', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'RESP']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traitée par')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['statut'], name='reclamation_statut_idx'), models.Index(fields=['priorite'], name='reclamation_priorite_idx'), models.Index(fields=['categorie'], name='reclamation_categorie_idx'), models.Index(fields=['etudiant', 'statut'], name='reclamation_etud_statut_idx')],
            },
        ),
    ]
