"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# ============================================================
# ENVIRONNEMENT / SÉCURITÉ
# ============================================================

def env_bool(nom, valeur_par_defaut=False):
    valeur = os.getenv(
        nom,
        str(valeur_par_defaut),
    )

    return valeur.strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


DEBUG = env_bool(
    "DJANGO_DEBUG",
    True,
)


# ------------------------------------------------------------
# SECRET KEY
# ------------------------------------------------------------

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY"
)

if not SECRET_KEY:
    if DEBUG:
        # Clé uniquement destinée au développement local.
        SECRET_KEY = (
            "django-insecure-gestioninternat-"
            "developpement-local-uniquement-2026"
        )
    else:
        raise RuntimeError(
            "DJANGO_SECRET_KEY doit être définie "
            "en production."
        )


# ------------------------------------------------------------
# ALLOWED HOSTS
# ------------------------------------------------------------

hosts_env = os.getenv(
    "DJANGO_ALLOWED_HOSTS",
    "",
)

if hosts_env:
    ALLOWED_HOSTS = [
        host.strip()
        for host in hosts_env.split(",")
        if host.strip()
    ]

elif DEBUG:
    ALLOWED_HOSTS = [
        "127.0.0.1",
        "localhost",
    ]

else:
    raise RuntimeError(
        "DJANGO_ALLOWED_HOSTS doit être défini "
        "en production."
    )


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "accounts",
    "etudiants",
    "hebergement",
    "finances",
    "reclamations",
    "notifications",
    "audit",
    "dashboard",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",

                "notifications.context_processors.notifications_non_lues",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# ============================================================
# VALIDATION DES MOTS DE PASSE
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
        "OPTIONS": {
            "min_length": 10,
        },
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fr-fr"
TIME_ZONE = "Africa/Casablanca"

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
AUTH_USER_MODEL = "accounts.Utilisateur"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ============================================================
# SÉCURITÉ HTTP
# ============================================================

if DEBUG:
    # --------------------------------------------------------
    # DÉVELOPPEMENT LOCAL
    # --------------------------------------------------------

    SECURE_SSL_REDIRECT = False

    SESSION_COOKIE_SECURE = False

    CSRF_COOKIE_SECURE = False

    SECURE_HSTS_SECONDS = 0

    SECURE_HSTS_INCLUDE_SUBDOMAINS = False

    SECURE_HSTS_PRELOAD = False

else:
    # --------------------------------------------------------
    # PRODUCTION HTTPS
    # --------------------------------------------------------

    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True

    # Commencer avec une durée raisonnable.
    # On pourra l'augmenter après validation HTTPS.
    SECURE_HSTS_SECONDS = int(
        os.getenv(
            "DJANGO_SECURE_HSTS_SECONDS",
            "3600",
        )
    )

    SECURE_HSTS_INCLUDE_SUBDOMAINS = False

    SECURE_HSTS_PRELOAD = False

# ============================================================
# SÉCURITÉ DES SESSIONS
# ============================================================

# Le cookie de session n'est jamais accessible
# directement depuis JavaScript.
SESSION_COOKIE_HTTPONLY = True

# Protection contre une partie des envois cross-site.
SESSION_COOKIE_SAMESITE = "Lax"

CSRF_COOKIE_SAMESITE = "Lax"

# 1 heure maximum d'inactivité.
SESSION_COOKIE_AGE = 60 * 60

# La session se termine lorsque le navigateur est fermé.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Une activité utilisateur renouvelle la durée de la session.
SESSION_SAVE_EVERY_REQUEST = True


# ============================================================
# AUTHENTIFICATION
# ============================================================

LOGIN_URL = "accounts:connexion"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/connexion/"