# Generated by Django 6.0.7 on 2026-07-15 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('VALIDATION', 'Validation'), ('REFUS', 'Refus'), ('ANNULATION', 'Annulation'), ('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('TRANSFERT', 'Transfert'), ('CLOTURE', 'Clôture'), ('AUTRE', 'Autre')], max_length=20, verbose_name="Type d'action")),
                ('entite', models.CharField(help_text='Exemple : DemandeHebergement, Affectation, Paiement.', max_length=100, verbose_name='Entité concernée')),
                ('identifiant_entite', models.CharField(blank=True, max_length=100, verbose_name="Identifiant de l'entité")),
                ('description', models.TextField(verbose_name="Description de l'action")),
                ('anciennes_valeurs', models.JSONField(blank=True, null=True, verbose_name='Anciennes valeurs')),
                ('nouvelles_valeurs', models.JSONField(blank=True, null=True, verbose_name='Nouvelles valeurs')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_historisees', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Historique d'action",
                'verbose_name_plural': 'Historique des actions',
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['utilisateur'], name='audit_utilisateur_idx'), models.Index(fields=['type_action'], name='audit_type_action_idx'), models.Index(fields=['entite', 'identifiant_entite'], name='audit_entite_id_idx'), models.Index(fields=['date_action'], name='audit_date_action_idx')],
            },
        ),
    ]
