# Generated by Django 6.0.7 on 2026-07-23 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='historiqueaction',
            name='audit_utilisateur_idx',
        ),
        migrations.RemoveIndex(
            model_name='historiqueaction',
            name='audit_type_action_idx',
        ),
        migrations.RemoveIndex(
            model_name='historiqueaction',
            name='audit_entite_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='historiqueaction',
            name='audit_date_action_idx',
        ),
        migrations.AlterField(
            model_name='historiqueaction',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historiqueaction',
            name='entite',
            field=models.CharField(max_length=100, verbose_name='Entité'),
        ),
        migrations.AlterField(
            model_name='historiqueaction',
            name='type_action',
            field=models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('VALIDATION', 'Validation'), ('ANNULATION', 'Annulation'), ('AFFECTATION', 'Affectation'), ('TRANSFERT', 'Transfert'), ('CLOTURE', 'Clôture'), ('TRAITEMENT', 'Traitement')], max_length=20, verbose_name="Type d'action"),
        ),
        migrations.AlterField(
            model_name='historiqueaction',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audit', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
