# Generated by Django 6.0.7 on 2026-07-15 13:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeUniversitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Exemple : 2026-2027', max_length=20, unique=True, verbose_name='Libellé')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('ACTIVE', 'Active'), ('CLOTUREE', 'Clôturée')], default='PLANIFIEE', max_length=10, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Année universitaire',
                'verbose_name_plural': 'Années universitaires',
                'ordering': ['-date_debut'],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__gt', models.F('date_debut'))), name='annee_date_fin_apres_date_debut'), models.UniqueConstraint(condition=models.Q(('statut', 'ACTIVE')), fields=('statut',), name='une_seule_annee_active')],
            },
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('nombre_etages', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name="Nombre d'étages")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('MAINTENANCE', 'En maintenance')], default='ACTIF', max_length=12, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Bâtiment',
                'verbose_name_plural': 'Bâtiments',
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('nombre_etages__gte', 1)), name='batiment_nombre_etages_positif')],
            },
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Numéro de chambre')),
                ('etage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Étage')),
                ('capacite', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité')),
                ('type_chambre', models.CharField(choices=[('INDIVIDUELLE', 'Individuelle'), ('DOUBLE', 'Double'), ('TRIPLE', 'Triple'), ('QUADRUPLE', 'Quadruple'), ('AUTRE', 'Autre')], default='DOUBLE', max_length=15, verbose_name='Type de chambre')),
                ('etat', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PARTIELLE', 'Partiellement occupée'), ('COMPLETE', 'Complète'), ('MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', max_length=15, verbose_name='État')),
                ('est_active', models.BooleanField(default=True, verbose_name='Chambre active')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chambres', to='hebergement.batiment', verbose_name='Bâtiment')),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'ordering': ['batiment__code', 'etage', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('batiment', 'numero'), name='numero_chambre_unique_par_batiment'), models.CheckConstraint(condition=models.Q(('capacite__gte', 1)), name='chambre_capacite_positive')],
            },
        ),
    ]
