# Generated by Django 6.0.7 on 2026-07-15 13:34

import django.core.validators
import django.db.models.deletion
import hebergement.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
        ('hebergement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeHebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(verbose_name='Motif de la demande')),
                ('distance_domicile', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distance du domicile en kilomètres')),
                ('situation_sociale', models.TextField(blank=True, verbose_name='Situation sociale')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire complémentaire')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('EN_ETUDE', "En cours d'étude"), ('INCOMPLETE', 'Incomplète'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('ATTENTE', "Liste d'attente"), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=12, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_soumission', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('date_decision', models.DateTimeField(blank=True, null=True, verbose_name='Date de décision')),
                ('motif_decision', models.TextField(blank=True, verbose_name='Motif ou observation de la décision')),
                ('annee_universitaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_hebergement', to='hebergement.anneeuniversitaire', verbose_name='Année universitaire')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_hebergement', to='etudiants.etudiant', verbose_name='Étudiant')),
                ('traitee_par', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'RESP']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traitée par')),
            ],
            options={
                'verbose_name': "Demande d'hébergement",
                'verbose_name_plural': "Demandes d'hébergement",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Justificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CIN', "Carte nationale d'identité"), ('CERT_INS', "Certificat d'inscription"), ('DOMICILE', 'Justificatif de domicile'), ('SOCIAL', 'Justificatif de situation sociale'), ('PHOTO', "Photo d'identité"), ('AUTRE', 'Autre document')], max_length=15, verbose_name='Type de document')),
                ('fichier', models.FileField(upload_to='hebergement/justificatifs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), hebergement.models.valider_taille_justificatif], verbose_name='Fichier')),
                ('nom_original', models.CharField(blank=True, max_length=255, verbose_name='Nom original du fichier')),
                ('statut_validation', models.CharField(choices=[('ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='ATTENTE', max_length=10, verbose_name='Statut de validation')),
                ('commentaire_validation', models.TextField(blank=True, verbose_name='Commentaire de validation')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to='hebergement.demandehebergement', verbose_name="Demande d'hébergement")),
            ],
            options={
                'verbose_name': 'Justificatif',
                'verbose_name_plural': 'Justificatifs',
                'ordering': ['type_document', '-date_ajout'],
            },
        ),
        migrations.AddIndex(
            model_name='demandehebergement',
            index=models.Index(fields=['statut'], name='demande_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='demandehebergement',
            index=models.Index(fields=['annee_universitaire', 'statut'], name='demande_annee_statut_idx'),
        ),
    ]
