# Generated by Django 6.0.7 on 2026-07-15 13:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
        ('hebergement', '0002_demandehebergement_justificatif_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree_prevue', models.DateField(verbose_name="Date d'entrée prévue")),
                ('date_entree_reelle', models.DateField(blank=True, null=True, verbose_name="Date d'entrée réelle")),
                ('date_sortie_prevue', models.DateField(verbose_name='Date de sortie prévue')),
                ('date_sortie_reelle', models.DateField(blank=True, null=True, verbose_name='Date de sortie réelle')),
                ('motif_sortie', models.TextField(blank=True, verbose_name='Motif de sortie')),
                ('statut', models.CharField(choices=[('PREVUE', 'Prévue'), ('ACTIVE', 'Active'), ('CLOTUREE', 'Clôturée'), ('ANNULEE', 'Annulée')], default='PREVUE', max_length=10, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('annee_universitaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='hebergement.anneeuniversitaire', verbose_name='Année universitaire')),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='hebergement.chambre', verbose_name='Chambre')),
                ('creee_par', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'RESP']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('demande_hebergement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='hebergement.demandehebergement', verbose_name="Demande d'hébergement")),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='etudiants.etudiant', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(verbose_name='Motif du transfert')),
                ('date_transfert', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du transfert')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('ancienne_affectation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfert_sortant', to='hebergement.affectation', verbose_name='Ancienne affectation')),
                ('effectue_par', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'RESP']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('nouvelle_affectation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfert_entrant', to='hebergement.affectation', verbose_name='Nouvelle affectation')),
            ],
            options={
                'verbose_name': 'Transfert',
                'verbose_name_plural': 'Transferts',
                'ordering': ['-date_transfert'],
            },
        ),
        migrations.AddIndex(
            model_name='affectation',
            index=models.Index(fields=['statut'], name='affectation_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='affectation',
            index=models.Index(fields=['chambre', 'statut'], name='affectation_chambre_idx'),
        ),
        migrations.AddIndex(
            model_name='affectation',
            index=models.Index(fields=['etudiant', 'statut'], name='affectation_etudiant_idx'),
        ),
        migrations.AddConstraint(
            model_name='affectation',
            constraint=models.CheckConstraint(condition=models.Q(('date_sortie_prevue__gte', models.F('date_entree_prevue'))), name='affectation_sortie_prevue_valide'),
        ),
    ]
