# Generated by Django 6.0.7 on 2026-07-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0003_affectation_transfert_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chambre',
            constraint=models.CheckConstraint(condition=models.Q(('etage__gte', 0)), name='chambre_etage_non_negatif'),
        ),
    ]
