# Generated by Django 6.0.7 on 2026-07-31 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
        ('hebergement', '0004_chambre_chambre_etage_non_negatif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='affectation',
            index=models.Index(fields=['annee_universitaire', 'statut'], name='affectation_annee_idx'),
        ),
        migrations.AddConstraint(
            model_name='affectation',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['PREVUE', 'ACTIVE'])), fields=('etudiant',), name='une_affectation_ouverte_par_etudiant'),
        ),
        migrations.AddConstraint(
            model_name='affectation',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['PREVUE', 'ACTIVE'])), fields=('demande_hebergement',), name='une_affectation_ouverte_par_demande'),
        ),
    ]
