# Generated by Django 6.0.7 on 2026-07-31 14:32

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0005_affectation_affectation_annee_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfert',
            options={'ordering': ['-date_transfert', '-date_creation'], 'verbose_name': 'Transfert', 'verbose_name_plural': 'Transferts'},
        ),
        migrations.AlterField(
            model_name='transfert',
            name='date_transfert',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date du transfert'),
        ),
        migrations.AddIndex(
            model_name='transfert',
            index=models.Index(fields=['date_transfert'], name='transfert_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='transfert',
            constraint=models.CheckConstraint(condition=models.Q(('ancienne_affectation', models.F('nouvelle_affectation')), _negated=True), name='transfert_affectations_differentes'),
        ),
    ]
