# Generated by Django 6.0.7 on 2026-08-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebergement', '0006_alter_transfert_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='justificatif',
            index=models.Index(fields=['demande', 'statut_validation'], name='justif_demande_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='justificatif',
            index=models.Index(fields=['type_document'], name='justif_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='justificatif',
            constraint=models.UniqueConstraint(condition=models.Q(('type_document', 'AUTRE'), _negated=True), fields=('demande', 'type_document'), name='justificatif_unique_par_type_demande'),
        ),
    ]
