# Generated by Django 6.0.7 on 2026-07-15 14:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        ('hebergement', '0003_affectation_transfert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraisHebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant total dû')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Frais actifs')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('annee_universitaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frais_hebergement', to='hebergement.anneeuniversitaire', verbose_name='Année universitaire')),
                ('cree_par', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'RESP']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frais_hebergement_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frais_hebergement', to='etudiants.etudiant', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': "Frais d'hébergement",
                'verbose_name_plural': "Frais d'hébergement",
                'ordering': ['-annee_universitaire__date_debut', 'etudiant__matricule'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant payé')),
                ('date_paiement', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date du paiement')),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement bancaire'), ('CARTE', 'Carte bancaire'), ('CHEQUE', 'Chèque'), ('AUTRE', 'Autre')], max_length=10, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Référence du paiement')),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='ATTENTE', max_length=10, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('motif_annulation', models.TextField(blank=True, verbose_name="Motif d'annulation")),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('enregistre_par', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'RESP']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('frais_hebergement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='finances.fraishebergement', verbose_name="Frais d'hébergement")),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement', '-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='fraishebergement',
            index=models.Index(fields=['annee_universitaire', 'est_actif'], name='frais_annee_actif_idx'),
        ),
        migrations.AddIndex(
            model_name='fraishebergement',
            index=models.Index(fields=['etudiant'], name='frais_etudiant_idx'),
        ),
        migrations.AddConstraint(
            model_name='fraishebergement',
            constraint=models.UniqueConstraint(fields=('etudiant', 'annee_universitaire'), name='frais_unique_etudiant_annee'),
        ),
        migrations.AddConstraint(
            model_name='fraishebergement',
            constraint=models.CheckConstraint(condition=models.Q(('montant_total__gt', 0)), name='frais_montant_total_positif'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut'], name='paiement_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date_paiement'], name='paiement_date_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['frais_hebergement', 'statut'], name='paiement_frais_statut_idx'),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='paiement_montant_positif'),
        ),
    ]
