# Generated by Django 6.0.7 on 2026-08-04 20:44

import django.core.validators
import finances.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='origine',
            field=models.CharField(choices=[('ADMIN', 'Administration'), ('ETUDIANT', 'Étudiant')], default='ADMIN', max_length=10, verbose_name='Origine de la déclaration'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='preuve_paiement',
            field=models.FileField(blank=True, null=True, upload_to='paiements/preuves/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), finances.models.valider_taille_preuve_paiement], verbose_name='Preuve de paiement'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['origine'], name='paiement_origine_idx'),
        ),
    ]
