# Generated by Django 6.0.7 on 2026-07-15 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('type_notification', models.CharField(choices=[('DEMANDE', "Demande d'hébergement"), ('AFFECTATION', 'Affectation'), ('PAIEMENT', 'Paiement'), ('RECLAMATION', 'Réclamation'), ('SYSTEME', 'Système')], default='SYSTEME', max_length=15, verbose_name='Type de notification')),
                ('est_lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('lien', models.CharField(blank=True, help_text='Exemple : /etudiant/demandes/5/', max_length=255, verbose_name='Lien interne')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'est_lue'], name='notification_user_lue_idx'), models.Index(fields=['type_notification'], name='notification_type_idx'), models.Index(fields=['date_creation'], name='notification_date_idx')],
            },
        ),
    ]
