# Generated by Django 6.0.7 on 2026-08-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='lien',
            field=models.CharField(blank=True, help_text='Exemple : /hebergement/etudiant/demandes/5/', max_length=255, verbose_name='Lien interne'),
        ),
    ]
