# Generated by Django 6.0.7 on 2026-07-13 12:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, unique=True, verbose_name='Matricule')),
                ('cne', models.CharField(max_length=20, unique=True, verbose_name='CNE')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1, verbose_name='Sexe')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('ville_origine', models.CharField(max_length=100, verbose_name="Ville d'origine")),
                ('filiere', models.CharField(max_length=150, verbose_name='Filière')),
                ('niveau_etude', models.CharField(max_length=100, verbose_name="Niveau d'étude")),
                ('telephone_contact_urgence', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Saisissez un numéro de téléphone valide.', regex='^\\+?[0-9 ]{9,20}$')], verbose_name="Téléphone du contact d'urgence")),
                ('nom_contact_urgence', models.CharField(max_length=150, verbose_name="Nom du contact d'urgence")),
                ('lien_contact_urgence', models.CharField(blank=True, max_length=100, verbose_name="Lien avec le contact d'urgence")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='etudiants/photos/', verbose_name='Photo')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('DIPLOME', 'Diplômé'), ('ABANDON', 'Abandon')], default='ACTIF', max_length=10, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_etudiant', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['utilisateur__last_name', 'utilisateur__first_name'],
            },
        ),
    ]
